### PR TITLE
fixing topmed columns

### PR DESCRIPTION
**Pull request by ACEnglish**
[column_map.txt](https://github.com/fakedrtom/SVAFotate/files/12043351/column_map.txt)
Following up on #10 
- Updated the conversion script to separate the incorrectly concatenated columns.
- Also fixed an issue with `EUR_Male_HomRef` being incorrectly overwritten on the autosome. 
- Removing duplicates during conversion.
- Attaching the `column_map.txt` to this PR so it is documented somewhere (this was part of where the OTH problem happened)
- Pasting the conversion script below

```python
import glob
import joblib
import pandas as pd

#SVAFotate header
header = ("CHROM START END SVLEN SVTYPE SOURCE "
          "SV_ID AF HomRef Het HomAlt Male_AF Male_HomRef "
          "Male_Het Male_HomAlt Male_HemiAlt Male_HemiAF "
          "Female_AF Female_HomRef Female_Het Female_HomAlt "
          "AFR_AF AFR_HomRef AFR_Het AFR_HomAlt AFR_Male_AF "
          "AFR_Male_HomRef AFR_Male_Het AFR_Male_HomAlt "
          "AFR_Male_HemiAlt AFR_Male_HemiAF AFR_Female_AF "
          "AFR_Female_HomRef AFR_Female_Het AFR_Female_HomAlt "
          "AMR_AF AMR_HomRef AMR_Het AMR_HomAlt AMR_Male_AF AMR_Male_HomRef "
          "AMR_Male_Het AMR_Male_HomAlt AMR_Male_HemiAlt "
          "AMR_Male_HemiAF AMR_Female_AF AMR_Female_HomRef "
          "AMR_Female_Het AMR_Female_HomAlt EAS_AF EAS_HomRef "
          "EAS_Het EAS_HomAlt EAS_Male_AF EAS_Male_HomRef EAS_Male_Het "
          "EAS_Male_HomAlt EAS_Male_HemiAlt EAS_Male_HemiAF EAS_Female_AF "
          "EAS_Female_HomRef EAS_Female_Het EAS_Female_HomAlt EUR_AF EUR_HomRef "
          "EUR_Het EUR_HomAlt EUR_Male_AF EUR_Male_HomRef EUR_Male_Het "
          "EUR_Male_HomAlt EUR_Male_HemiAlt EUR_Male_HemiAF EUR_Female_AF "
          "EUR_Female_HomRef EUR_Female_Het EUR_Female_HomAlt OTH_AF "
          "OTH_HomRef OTH_Het OTH_HomAlt OTH_Male_AF OTH_Male_HomRef "
          "OTH_Male_Het OTH_Male_HomAlt OTH_Male_HemiAlt OTH_Male_HemiAF "
          "OTH_Female_AF OTH_Female_HomRef OTH_Female_Het OTH_Female_HomAlt "
          "SAS_AF SAS_HomRef SAS_Het SAS_HomAlt SAS_Male_AF SAS_Male_HomRef "
          "SAS_Male_Het SAS_Male_HomAlt SAS_Male_HemiAlt SAS_Male_HemiAF "
          "SAS_Female_AF SAS_Female_HomRef SAS_Female_Het SAS_Female_HomAlt "
          "PopMax_AF InPop")
header = header.split(' ')

# VCF INFO to SVAFotate column translation
col_map = {}
with open("column_map.txt", 'r') as fh:
    for line in fh:
        d = line.strip().split('\t')
        col_map[d[0]] = d[1]
        
# Load dataframes, dedup/rename columns
files = glob.glob("/Users/english/Downloads/dframes/*.jl")
data = (pd.concat([joblib.load(_) for _ in files])
            .drop(columns=["END", "SVTYPE", "SVLEN"])
            .rename(columns=col_map))

# PASS only
data['filter'] = data['filter'].apply(lambda x: x[0])
data = data[data['filter'] == "PASS"].copy()

# Fix chromosome
data['CHROM'] = data["CHROM"].str.replace("chr", "")

# Pull out counts (except X which has nan)
data["HomRef"] = data["GTCNT"].apply(lambda x: x[1] if not isinstance(x, float) else x)
data["Het"] = data["GTCNT"].apply(lambda x: x[2] if not isinstance(x, float) else x)
data["HomAlt"] = data["GTCNT"].apply(lambda x: x[3] if not isinstance(x, float) else x)

# Fix tuple types
for i in [_ for _ in data.columns if "AC" in _] + ["AF"]:
     data[i] = data[i].apply(lambda x: x[0] if isinstance(x, tuple) else x)
        
# Calculate new columns
data["SOURCE"] = "TOPMed"
data["PopMax_AF"] = data[["AFR_AF", "AMR_AF", "EAS_AF", "EUR_AF", "OTH_AF", "SAS_AF"]].max(axis=1)
data["InPop"] = (data[["AFR_AF", "AMR_AF", "EAS_AF", "EUR_AF", "OTH_AF", "SAS_AF"]] != 0).sum(axis=1)

# Hemi only applies to some of chrX and is just AC_Male/AF_Male
missing_cols = ['Male_HemiAlt', 'AFR_Male_HemiAlt', 'AMR_Male_HemiAlt', 'EAS_Male_HemiAlt', 'EUR_Male_HemiAlt', 
                'OTH_Male_HemiAlt', 'SAS_Male_HemiAlt', 'Male_HemiAF', 'AFR_Male_HemiAF', 'AMR_Male_HemiAF', 
                'EAS_Male_HemiAF', 'EUR_Male_HemiAF', 'OTH_Male_HemiAF', 'SAS_Male_HemiAF']
data[missing_cols] = 0
alter_subset = (data["CHROM"] == "X") & (data["N_HEMI_Male"] != 0)
for s_key, d_key in [("", ""), ("AFR_", "_AFR"), ("EAS_", "_EAS"), ("EUR_", "_EUR"), ("OTH_", "_MES"), ("SAS_", "_SAS")]:
    data.loc[alter_subset, s_key + "Male_HemiAlt"] = data[alter_subset]["AC_Male" + d_key]
    data.loc[alter_subset, s_key + "Male_HemiAF"] = data[alter_subset][s_key + "Male_AF"]

# Have to fill in chrX's GT counts
for col in ["HomRef", "Het", "HomAlt"]:
    sub = data[col].isna()
    data.loc[sub, col] = data.loc[sub, "Male_" + col] + data.loc[sub, "Female_" + col]
    # Counts
    data[col] = data[col].astype(int)

# Save
(data[header].sort_values(["CHROM", "START", "END"])
     .drop_duplicates(subset="CHROM START END SVLEN SVTYPE SOURCE".split(' '))
     .rename(columns={"CHROM":"#CHROM"})
     .to_csv("SVAFotate_core_TopMed_SV_popAFs.GRCh38.bed", sep='\t', index=False))
```

### CODE REVIEW

**Comment by fakedrtom** [comment]
Thank you, Adam. The header appears to be fixed, but I think there is still a missing column in the data:

```
OTH_AF	OTH_HomRef	OTH_Het	OTH_HomAlt
0.0	342	0	0.0
0.0	340	0	0.0
0.0	287	0	0.0
0.0	339	0	0.0
0.0	321	0	0.0
0.0	332	0	0.0
0.0	288	0	0.0
0.0	311	0	0.0
0.0655488	285	0	0.0829384
```
OTH_AF and OTH_HomRef appear to be as expected, but I suspect that the actual OTH_Het count is missing and it is skipping to the OTH_HomAlt count. I am basing that on the DEL_1:821037-821907 deletion which shows the following:

```OTH_AF	OTH_HomRef	OTH_Het	OTH_HomAlt	OTH_Male_AF	OTH_Male_HomRef	OTH_Male_Het	OTH_Male_HomAlt	OTH_Male_HemiAlt	OTH_Male_HemiAF	OTH_Female_AF	OTH_Female_HomRef	OTH_Female_Het	OTH_Female_HomAlt
0.0655488	285	0	0.0829384	176	35	0	0	0.0	0.034188	109	8	0	0.0442616
```

The male and female HomRef counts add up to 285 but it looks like there should be a Het count of 43 and 0 HomAlts. From reviewing your code, I thought that fixing the header would also add the OTH_Het column data to the file, but I think it is still being skipped somehow.

**Comment by ACEnglish** [comment]
I'm unable to recreate the problem you're seeing. When I look at the example DEL you mentioned I see:
```
d2 = pd.read_csv("TOPMed.GRCh38.bed.gz", sep='\t')
d2[d2['SV_ID'] == 'DEL_1:821037-821907'][["OTH_AF", "OTH_HomRef", "OTH_Het", "OTH_HomAlt", "OTH_Male_AF"]]
#8  0.065549         285       43           0     0.082938
```
And outside of pandas:
```
$ zgrep "#CHROM\|DEL_1:821037-821907" TOPMed.GRCh38.bed.gz | cut -f78-82
OTH_AF  OTH_HomRef      OTH_Het OTH_HomAlt      OTH_Male_AF
0.0655488       285     43      0       0.0829384
```

Are you sure you're looking at the correct file? Mine's md5sum is:
`c5d19b26bcc061b502a163ee1174afbc  TOPMed.GRCh38.bed.gz`

**Comment by fakedrtom** [comment]
I apologize, looks like I had a mislabeled file and that was causing me to unknowingly look at an older file. Everything appears to be in order I think. I've tested it out and it ran successfully. Thanks again for all your help with this! I have acknowledged you in the repo's READMEs, but is there any other way I can properly credit you?

**Comment by ACEnglish** [comment]
Its all good. Happy to help!

**Pull request merged**
